trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  name: P12Certificate
  displayName: 'Download P12 Secure Certificate'
  inputs:
    secureFile: '<p12 certificate file name>'

- task: DownloadSecureFile@1
  name: ProvisionCertificate
  displayName: 'Download Mobile Provision Certificate'
  inputs:
    secureFile: '<provisioning profile file name>'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '<p12 certificate file name>'
    certPwd: 'xxxxxxxxxxx'
    keychain: 'xxxxxxx'
  displayName: 'Installation of P12 Certificate'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '<provisioning profile file name>'
  displayName: 'Installation Provisioning Profile'

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    cordova platform add ios@5.0.0
  displayName: 'Adding IOS Platoform'

- script: |
    cordova build ios --release --device --buildFlag='-UseModernBuildSystem=0'
  displayName: 'Generating IOS App'

- task: CmdLine@2
  inputs:
    script: 'rm -f $(Agent.WorkFolder)/platforms/ios/build/device/<your app name>.app'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.WorkFolder)'
    Contents: 'platforms/ios/build/device/<your app name>.ipa'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: false
    overWrite: false
    flattenFolders: false
    preserveTimestamp: true
  displayName: 'Copying IOS IPA as Artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'CordovaMobileApps'
    artifactType: 'container'