# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Install Dependencies, Lint, Build and Test

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install Dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    
    - name: Build
      run: npm run build -- --prod
   
    - name: Test
      run: npm test -- --configuration=ci
      
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Installing cordova
      run: npm i -g cordova@latest
    
    - name: Build android App using cordova
      run: npx ionic cordova build android --no-build --release

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
       name: app
       path: app/build/outputs/apk/release/app-release-unsigned.apk
